import { UserInsert } from '@app/db/schema';
import { ids } from './ids';
import {
  AdminPermission,
  CommunicationManagePermission,
  DeliveryCreatePermission,
  DeliveryListPermission,
  DeliveryViewPermission,
  FileUploadPermission,
  FileViewBuildingPermission,
  FileViewResidencyPermission,
  MaintenanceClosePermission,
  MaintenanceInternalCommentPermission,
  MaintenanceTriagePermission,
  MaintenanceViewBuildingPermission,
  MaintenanceViewResidencyPermission,
  MaintenanceWorkPermission,
  ReservationCreatePermission,
  ReservationViewBuildingPermission,
  ReservationViewResidencyPermission,
  UserManagePermission,
  VisitorCreatePermission,
  VisitorViewPermission,
} from '@app/permissions';

const residentPermissions = [
  ReservationCreatePermission,
  ReservationViewResidencyPermission,
  DeliveryViewPermission,
  VisitorCreatePermission,
  FileViewResidencyPermission,
  MaintenanceViewResidencyPermission,
];

const employeePermissions = [
  UserManagePermission,
  CommunicationManagePermission,
  ReservationViewBuildingPermission,
  DeliveryCreatePermission,
  DeliveryListPermission,
  VisitorCreatePermission,
  VisitorViewPermission,
  FileUploadPermission,
  FileViewBuildingPermission,
  MaintenanceViewBuildingPermission,
  MaintenanceTriagePermission,
  MaintenanceWorkPermission,
  MaintenanceClosePermission,
  MaintenanceInternalCommentPermission,
];

export const userData: UserInsert[] = [
  {
    id: ids.users.joao,
    accountId: ids.accounts.joao,
    residencyId: ids.residencies.ap101,
    buildingId: ids.buildings.jardim,
    name: 'João Silva',
    permissions: residentPermissions,
    active: true,
  },
  {
    id: ids.users.maria,
    accountId: ids.accounts.maria,
    residencyId: ids.residencies.ap102,
    buildingId: ids.buildings.jardim,
    name: 'Maria Silva',
    permissions: residentPermissions,
    active: true,
  },
  {
    id: ids.users.carlos,
    accountId: ids.accounts.carlos,
    residencyId: ids.residencies.casa01,
    buildingId: ids.buildings.bosque,
    name: 'Carlos Souza',
    permissions: residentPermissions,
    active: true,
  },
  {
    id: ids.users.beatriz,
    accountId: ids.accounts.beatriz,
    residencyId: ids.residencies.casa02,
    buildingId: ids.buildings.bosque,
    name: 'Beatriz Lima',
    permissions: residentPermissions,
    active: true,
  },
  {
    id: ids.users.ana,
    accountId: ids.accounts.ana,
    residencyId: null,
    buildingId: ids.buildings.jardim,
    name: 'Ana Recepção',
    permissions: employeePermissions,
    active: true,
  },
  {
    id: ids.users.fernanda,
    accountId: ids.accounts.fernanda,
    residencyId: null,
    buildingId: ids.buildings.jardim,
    name: 'Fernanda Síndica',
    permissions: [AdminPermission],
    active: true,
  },
  {
    id: ids.users.rafael,
    accountId: ids.accounts.rafael,
    residencyId: null,
    buildingId: ids.buildings.bosque,
    name: 'Rafael Portaria',
    permissions: employeePermissions,
    active: true,
  },
  {
    id: ids.users.luciana,
    accountId: ids.accounts.luciana,
    residencyId: null,
    buildingId: ids.buildings.bosque,
    name: 'Luciana Síndica',
    permissions: [AdminPermission],
    active: true,
  },
];
