version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminPasswd
    volumes:
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql

  db-dashboard:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 9000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: adminPasswd
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    
  minio:
    image: minio/minio:latest
    container_name: minio-emp
    ports:
      - "9090:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
