CREATE DATABASE "authDb";
CREATE DATABASE "coreDb";
CREATE DATABASE "deliveryDb";
CREATE DATABASE "reservationDb";
CREATE DATABASE "communicationDb";
CREATE DATABASE "visitorDb";
CREATE DATABASE "fileDb";
CREATE DATABASE "maintenanceDb";
